# Generated by Django 5.0.1 on 2024-01-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_age', models.PositiveIntegerField()),
                ('student_dob', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='book_id',
            field=models.IntegerField(unique=True),
        ),
    ]
